// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/cloudfoundry/blobstore_url_signer/signer"
)

type FakeSigner struct {
	SignStub        func() string
	signMutex       sync.RWMutex
	signArgsForCall []struct{}
	signReturns     struct {
		result1 string
	}
}

func (fake *FakeSigner) Sign() string {
	fake.signMutex.Lock()
	fake.signArgsForCall = append(fake.signArgsForCall, struct{}{})
	fake.signMutex.Unlock()
	if fake.SignStub != nil {
		return fake.SignStub()
	} else {
		return fake.signReturns.result1
	}
}

func (fake *FakeSigner) SignCallCount() int {
	fake.signMutex.RLock()
	defer fake.signMutex.RUnlock()
	return len(fake.signArgsForCall)
}

func (fake *FakeSigner) SignReturns(result1 string) {
	fake.SignStub = nil
	fake.signReturns = struct {
		result1 string
	}{result1}
}

var _ signer.Signer = new(FakeSigner)
